version: '3.7'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: remindme
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  rabbitmq:
    image: remindme/rabbitmq
    build:
      context: ./docker/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: usr
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
      - "15672:15672"