// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: channel.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channel (user_id, created_at, settings, verification_token, verified_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, created_at, settings, verification_token, verified_at
`

type CreateChannelParams struct {
	UserID            int64
	CreatedAt         time.Time
	Settings          pgtype.JSONB
	VerificationToken sql.NullString
	VerifiedAt        sql.NullTime
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.UserID,
		arg.CreatedAt,
		arg.Settings,
		arg.VerificationToken,
		arg.VerifiedAt,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.Settings,
		&i.VerificationToken,
		&i.VerifiedAt,
	)
	return i, err
}
