// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: channel.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channel (user_id, created_at, settings, is_verified)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, created_at, settings, is_verified
`

type CreateChannelParams struct {
	UserID     int64
	CreatedAt  time.Time
	Settings   pgtype.JSONB
	IsVerified bool
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.UserID,
		arg.CreatedAt,
		arg.Settings,
		arg.IsVerified,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.Settings,
		&i.IsVerified,
	)
	return i, err
}
