// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const activateUser = `-- name: ActivateUser :one
UPDATE "user" 
SET activated_at = $1::timestamp, activation_token = null
WHERE activation_token = $2::text
RETURNING id, email, identity, password_hash, created_at, activated_at, activation_token
`

type ActivateUserParams struct {
	ActivatedAt     time.Time
	ActivationToken string
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, activateUser, arg.ActivatedAt, arg.ActivationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Identity,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.ActivationToken,
	)
	return i, err
}

const createLimits = `-- name: CreateLimits :one
INSERT INTO limits (
    user_id, 
    email_channel_count, 
    telegram_channel_count, 
    active_reminder_count, 
    monthly_sent_reminder_count,
    reminder_every_per_day_count
) 
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, email_channel_count, telegram_channel_count, active_reminder_count, monthly_sent_reminder_count, reminder_every_per_day_count
`

type CreateLimitsParams struct {
	UserID                   int64
	EmailChannelCount        sql.NullInt32
	TelegramChannelCount     sql.NullInt32
	ActiveReminderCount      sql.NullInt32
	MonthlySentReminderCount sql.NullInt32
	ReminderEveryPerDayCount sql.NullFloat64
}

func (q *Queries) CreateLimits(ctx context.Context, arg CreateLimitsParams) (Limit, error) {
	row := q.db.QueryRow(ctx, createLimits,
		arg.UserID,
		arg.EmailChannelCount,
		arg.TelegramChannelCount,
		arg.ActiveReminderCount,
		arg.MonthlySentReminderCount,
		arg.ReminderEveryPerDayCount,
	)
	var i Limit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailChannelCount,
		&i.TelegramChannelCount,
		&i.ActiveReminderCount,
		&i.MonthlySentReminderCount,
		&i.ReminderEveryPerDayCount,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO session (token, user_id, created_at)
VALUES ($1, $2, $3)
RETURNING id, token, user_id, created_at
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	CreatedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Token, arg.UserID, arg.CreatedAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (email, identity, password_hash, created_at, activated_at, activation_token) 
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, identity, password_hash, created_at, activated_at, activation_token
`

type CreateUserParams struct {
	Email           sql.NullString
	Identity        sql.NullString
	PasswordHash    sql.NullString
	CreatedAt       time.Time
	ActivatedAt     sql.NullTime
	ActivationToken sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Identity,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.ActivatedAt,
		arg.ActivationToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Identity,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.ActivationToken,
	)
	return i, err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :one
DELETE FROM session WHERE token = $1 RETURNING user_id
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRow(ctx, deleteSessionByToken, token)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, identity, password_hash, created_at, activated_at, activation_token FROM "user" WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Identity,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.ActivationToken,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, identity, password_hash, created_at, activated_at, activation_token FROM "user" WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Identity,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.ActivationToken,
	)
	return i, err
}

const getUserBySessionToken = `-- name: GetUserBySessionToken :one
SELECT "user".id, "user".email, "user".identity, "user".password_hash, "user".created_at, "user".activated_at, "user".activation_token FROM "user" 
JOIN session ON "user".id = session.user_id
WHERE session.token = $1
`

func (q *Queries) GetUserBySessionToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySessionToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Identity,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.ActivationToken,
	)
	return i, err
}

const getUserLimitsWithLock = `-- name: GetUserLimitsWithLock :one
SELECT id, user_id, email_channel_count, telegram_channel_count, active_reminder_count, monthly_sent_reminder_count, reminder_every_per_day_count FROM limits WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) GetUserLimitsWithLock(ctx context.Context, userID int64) (Limit, error) {
	row := q.db.QueryRow(ctx, getUserLimitsWithLock, userID)
	var i Limit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailChannelCount,
		&i.TelegramChannelCount,
		&i.ActiveReminderCount,
		&i.MonthlySentReminderCount,
		&i.ReminderEveryPerDayCount,
	)
	return i, err
}

const setPassword = `-- name: SetPassword :one
UPDATE "user"
SET password_hash = $1::text
WHERE id = $2::bigint
RETURNING id
`

type SetPasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) (int64, error) {
	row := q.db.QueryRow(ctx, setPassword, arg.PasswordHash, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
