// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (email, identity, password_hash, created_at, activated_at, activation_token) 
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, identity, password_hash, created_at, activated_at, activation_token, last_login_at
`

type CreateUserParams struct {
	Email           sql.NullString
	Identity        sql.NullString
	PasswordHash    sql.NullString
	CreatedAt       time.Time
	ActivatedAt     sql.NullTime
	ActivationToken sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Identity,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.ActivatedAt,
		arg.ActivationToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Identity,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.ActivationToken,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, identity, password_hash, created_at, activated_at, activation_token, last_login_at FROM "user" WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Identity,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.ActivationToken,
		&i.LastLoginAt,
	)
	return i, err
}
